//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsArtOrders.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOrdersEntities : DbContext
    {
        private static DbOrdersEntities _context;
        public static DbOrdersEntities GetContext()
        {
            if (_context == null)
                _context = new DbOrdersEntities();
            return _context;
        }
        public DbOrdersEntities()
            : base("name=DbOrdersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employee_Order> Employee_Order { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Orderers> Orderers { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
    }
}
