//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsArtOrders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int OrdererId { get; set; }
        public string Orderer_Name { get; set; }
        public string Orderer_Surname { get; set; }
        public string Orderer_Patronimyc { get; set; }
        public string Orderer_Phone { get; set; }
        public string Orderer_Email { get; set; }
        public string Orderer_Organization { get; set; }
        public string Orderer_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
